# name: CI

# on:
#   push:
#     branches: [main, master]
#   pull_request:
#     branches: [main, master]

# concurrency:
#   group: ci-${{ github.ref }}
#   cancel-in-progress: true

# jobs:
#   go-api:
#     name: Go API
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: StockTracker.API
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-go@v5
#         with:
#           go-version: "1.22"
#       - name: Tidy
#         run: go mod tidy
#       - name: Build
#         run: go build ./cmd/api
#       - name: Test
#         run: go test ./...
#       - name: Lint
#         uses: golangci/golangci-lint-action@v6
#         with:
#           version: v1.59
#           working-directory: StockTracker.API

#   python-collector:
#     name: Python Collector
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: StockTracker.Collector
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-python@v5
#         with:
#           python-version: "3.11"
#       - name: Install
#         run: |
#           python -m pip install --upgrade pip
#           pip install -e .[dev]
#       - name: Lint
#         run: |
#           ruff check .
#           black --check .
#           mypy src
#       - name: Test
#         run: pytest -q

#   ui-next:
#     name: Next.js UI
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: StockTracker.UI
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: "20"
#           cache: "npm"
#           cache-dependency-path: StockTracker.UI/package-lock.json
#       - name: Install
#         run: |
#           if [ -f package-lock.json ]; then npm ci; else npm i; fi
#       - name: Lint
#         run: npm run lint -- --no-error-on-unmatched-pattern
#       - name: Build
#         run: npm run build
